### ISSUE TITLE
How to Secure API token - Article Submission Request

### ISSUE THREAD

**Issue by MaheshtheDev** [genicsblog/genicsblog.github.io#45]
### Idea
In this IT world, securing the data transfer is tough. 
But securing the API with token is important.
So, i wrote on `How to Secure API token`

### Topics

**Category**: Web

**Tags**: API, Backend-Security, Web-Development

### Cross-posting?
https://maheshthedev.hashnode.dev/how-to-secure-api-token

**Comment by gouravkhunger** [comment]
Thanks for the article request! You could start by adding a new draft in the `_drafts` folder. Here are the steps for that: https://docs.genicsblog.com/author/writing-the-article

The file name could be `how-to-secure-an-api-token.md`. Quick note: use your username as defined in the contributors.yml file(MaheshtheDev) for the `author` field in the markdown front matter. Reference for other variables is explained in the documentation. To preview how your draft would look like on the website, here's a few things to keep in mind:

- Don't change other's draft: that might cause PR checks to fail.
- Don't add commits where files outside the `_drafts` folder have been changed: same, pr checks will fail.

If the checks pass, the draft will be auto merged causing the site to publish your draft- which would appear in about 2 minutes at: `https://genicsblog.com/draft/<name of your file>`(example: `https://genicsblog.com/draft/how-to-secure-an-api-token`).

If you ever need support, you can get back here in the same thread!

**Comment by gouravkhunger** [comment]
[Your post](https://genicsblog.com/MaheshtheDev/how-to-secure-api-tokens) is live now. Congrats!
