### ISSUE TITLE
Cross post: Make a toast with HTML, CSS, and JS

### ISSUE THREAD

**Issue by AnishDe12020** [genicsblog/genicsblog.github.io#48]
### Idea

Blog about creating a toast notification with HTML, CSS and JS

### Topics

**Category**: web

**Tags**: web-development, beginners

### Cross-posting?

https://blog.anishde.dev/make-a-toast-with-html-css-and-js

**Comment by gouravkhunger** [comment]
Nice topic! You could start by adding a new draft in the `_drafts` folder. Here are the steps for that: https://docs.genicsblog.com/author/writing-the-article

The file name could be `make-a-toast-with-html-css-and-js.md`. Quick note: use your username as defined in the contributors.yml file(anishde12020) for the `author` field in the markdown. Reference for other variables is explained in the documentation. To preview how your draft would look like on the website, here's a few things to keep in mind:

- Don't change other's draft: that might cause PR checks to fail.
- Don't add commits where files outside the `_drafts` folder have been changed: same, pr checks will fail.

If the checks pass, the draft will be auto merged causing the site to publish your draft- which would appear in about 2 minutes at: `https://genicsblog.com/draft/<name of your file>`(example: `https://genicsblog.com/draft/make-a-toast-with-html-css-and-js`).

And I see your article requires codepen blocks, don't add them in the draft yet. I will add support for them within the time your draft is done. If you ever need support, you can get back here in the same thread!

**Comment by gouravkhunger** [comment]
@AnishDe12020 Thanks for the contribution and congrats on getting your first article published! 🎉 

The markdown file for your post is available [here](https://github.com/genicsblog/genicsblog.github.io/blob/main/_posts/web/2022-01-07-making-a-toast-notification-with-html-css-and-js.md). If you ever want to edit it, you can make a PR!

And [here's the live link](https://genicsblog.com/anishde12020/making-a-toast-notification-with-html-css-and-js) for the post 😄
