### ISSUE TITLE
5 Web Development Projects You can make to Polish Your Skills - Submission Request

### ISSUE THREAD

**Issue by RainboeStrykr** [genicsblog/genicsblog.github.io#71]
### Idea

If you are also interested in web development, the best way to create experience in this field is to work on web development projects. 
A list of 5 webdev projects you can make to polish your skills

### Topics

**Category**: web

**Tags**:  web-development, beginners, tips

### Cross-posting?

NO

**Comment by gouravkhunger** [comment]
Nice, you can go ahead and [Create the draft](https://docs.genicsblog.com/author/writing-the-article)!

**Comment by gouravkhunger** [comment]
[The post](https://genicsblog.com/five-projects-to-become-better-at-webdev) is published 🎉
