### ISSUE TITLE
Post idea: 6 free websites to learn web3.0

### ISSUE THREAD

**Issue by aditya-singh9** [genicsblog/genicsblog.github.io#72]
### Idea
6 free websites to learn web3.0

### Topics

**Category**: web3

**Tags**: #begginers, #blockchain

### Cross-posting?

This is my original post here.

### Remarks
 No remarks.

**Comment by gouravkhunger** [comment]
Great, you can [create a draft](https://docs.genicsblog.com/author/writing-the-article) for this article and we'll review it!

P.S.: You need a [contributor profile](https://docs.genicsblog.com/getting-started#make-a-contributor-profile) first.

**Comment by gouravkhunger** [comment]
Congrats on getting your [first post](https://genicsblog.com/6-free-websites-to-learn-web3) published!
