### ISSUE TITLE
Intro to GraphQL with Node.js and TypeScript

### ISSUE THREAD

**Issue by carrotfarmer** [genicsblog/genicsblog.github.io#75]
### Idea
This article explains how you can set up a GraphQL server with Apollo and create a schema using TypeGraphQL with CRUD operations using TypeORM and PostgreSQL.

### Topics
**Category**: backend

**Tags**: nodejs, API, web-development

### Cross-posting?
https://thecatblog.hashnode.dev/intro-to-graphql-with-nodejs-and-typescript

**Comment by gouravkhunger** [comment]
Thanks for the cross-post idea! You can move to the next steps and [create a draft post](https://docs.genicsblog.com/author/writing-the-article). Once you are done with the draft, ping us here and we'll review it!

Also, consider joining [our discord server](https://discord.genicsblog.com) so we could add you as a qualified author once the article gets published.

**Comment by carrotfarmer** [comment]
@gouravkhunger I made the draft in #77

**Comment by gouravkhunger** [comment]
Hey @carrotfarmer. Since it was correct in terms of frontmatter, it got auto merged. It is done so that authors can preview the draft asap. Here's [the link](https://genicsblog.com/draft/intro-to-graphql-with-node-and-typescript) to the draft.

We'll review the draft and publish it within a day. The draft needs some formatting fixes, we'll do that for you. Thanks for the contribution!

**Comment by carrotfarmer** [comment]
@gouravkhunger Thanks!

**Comment by gouravkhunger** [comment]
Hey @carrotfarmer We've done the code-block formatting fixes. Congrats on getting [your first post](https://genicsblog.com/dhruva/intro-to-graphql-with-node-and-typescript) published! 

We'll share it on twitter too, so if you want to get tagged you can send us your Twitter handle, as it seems you haven't added it on [your profile](https://genicsblog.com/contributor/dhruva)

**Comment by carrotfarmer** [comment]
@gouravkhunger Thanks for the fixes and I don't have Twitter 😆
So it's fine if you don't tag me :)

**Comment by gouravkhunger** [comment]
Oh, it's ok 👍 
I'm closing the issue now! You're welcome to post new articles anytime :)
